### ISSUE TITLE
color handling broke piping to git pile am

### ISSUE THREAD

**Issue by jnikula** [git-pile/git-pile#73]
Trying to pipe a patch to `git pile am`:

```
Traceback (most recent call last):
  File "/path/to/bin/git-pile", line 12, in <module>
    sys.exit(git_pile.main(*sys.argv[1:]))
  File "/path/to/src/git-pile/git_pile/git_pile.py", line 2027, in main
    return args.func(args)
  File "/path/to/src/git-pile/git_pile/git_pile.py", line 981, in cmd_am
    info("Entering '%s' directory" % config.dir)
  File "/path/to/src/git-pile/git_pile/helpers.py", line 127, in info
    print_color(color, "‣", s, *args, **kwargs)
  File "/path/to/src/git-pile/git_pile/helpers.py", line 121, in print_color
    sl = [ color + prefix, s, *args, COLOR_RESET ]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Bisect result:

```
80e5f05b578cb14ae8ed083dcdf6441c137ce5b9 is the first bad commit
commit 80e5f05b578cb14ae8ed083dcdf6441c137ce5b9
Author: Lucas De Marchi <lucas.demarchi@intel.com>
Date:   Tue Mar 15 09:29:42 2022 -0700

    helpers: improve color handling in logs
    
    Add some color definitions and use yellow for warnings.
    
    Signed-off-by: Lucas De Marchi <lucas.demarchi@intel.com>

 git_pile/helpers.py | 34 ++++++++++++++++++++++------------
 1 file changed, 22 insertions(+), 12 deletions(-)


```

**Comment by lucasdemarchi** [comment]
works for me  with python 3.9.7. But I guess I can simply s/None/""/

**Comment by lucasdemarchi** [comment]
oh... just understood what happens. The problem is not piping something to git-pile, but rather redirecting the output. I'm adding a few more patches to improve this.
